// Code generated by xgo (XGo); DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/Sky-Runner-Z/Xgo-gredis"
)

const _ = true

type index struct {
	gredis.Client
}
//line index.redis:1
func (this *index) MainEntry() {
//line index.redis:1:1
	this.Set("user:1001", "john", 360000000)
//line index.redis:3:1
	fmt.Println(this.Get("user:1001"))
}
func (this *index) Main() {
	gredis.Gopt_Client_Main(this)
}
func main() {
	new(index).Main()
}
